### ISSUE TITLE
When the pose is corrected, the previously distorted map will also be corrected, right?

### ISSUE THREAD

**Issue by ZZy129326999** [Jarrome/IMT_Mapping#2]
Hi, I have some questions. When the pose is corrected, the previously distorted map will also be corrected, right?

**Comment by ZZy129326999** [comment]
> Hi, I have some questions. When the pose is corrected, the previously distorted map will also be corrected, right?

Hello

**Comment by Jarrome** [comment]
Hi, ZZy,

Sorry the github doesnot notify me... I just find this issue.

Yes, when pose is corrected, the corresponding local map will be (1) deintegrated from global, (2) transformed and (3) integrated to global.

Very best,
Yijun
